#!/bin/bash

extract () {
 	ffmpeg -i "${PWD}$1" -c:a copy -vn ${PWD}/src/main/resources/movies/audio.mp4
}

echo $1
echo $PWD

if [[ ! -f ${PWD}$1 ]]
then 
	echo "File not found" >&2
elif [[ ${PWD}$1 = *.webm ]]
then 
	echo "Webm extension is not supported yet" >&2
elif [[ ${PWD}$1 = *.mp4 ]]
then 
	extract $1
	echo "Audio extraction succeeded and produced audio_$1"
	exit 0
fi

exit 1
