#!/bin/bash

convert_to_480p () {
	ffmpeg -i "${PWD}$1" -an -c:v libx264 -x264opts 'keyint=24:min-keyint=24:no-scenecut' -b:v $2 -maxrate $3k -bufsize $4k -vf 'scale=-1:$5' ${PWD}/src/main/resources/movies/720_$1 || { echo "Something went wrong trying to convert $1"; exit 1; }
}

if [[ ! -f ${PWD}$1 ]]
then 
	echo "File not found" >&2
elif [[ ${PWD}$1 = *.webm ]]
then 
	echo "Webm extension is not supported yet" >&2
elif [[ ${PWD}$1 = *.mp4 ]]
then 
	convert_to_480p $1 $2 $3 $4 $5
fi

exit 1
